@startuml
node "Cortex Workstation" {
    [GUI - DGNA Cortette] <--> [TetraClient]
} 

node "Tetra Gateway edit" {
    [RadQServer] <--> [CADIService]
folder "RadQServerDGNARecords.xml"
    [RadQServer] <--> [RadQServerDGNARecords.xml]
} 

cloud "Tetra Provider"



[TetraClient] <--> [RadQServer]
[CADIService] <--> [Tetra Provider]
@enduml
